# Generated by Django 6.0 on 2026-01-03 22:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(help_text='A, B, C...', max_length=10)),
                ('is_occupied', models.BooleanField(default=False)),
                ('iot_meter_id', models.CharField(blank=True, help_text='USP #5', max_length=100, null=True, unique=True)),
                ('public_uid', models.UUIDField(default=uuid.uuid4, help_text='USP #3: Public share link', unique=True)),
                ('last_occupied_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=50, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=50, null=True)),
                ('license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('established_year', models.IntegerField(blank=True, null=True)),
                ('total_floors', models.IntegerField(default=1)),
                ('property_type', models.CharField(choices=[('BOYS', 'Boys'), ('GIRLS', 'Girls'), ('CO_ED', 'Co-Ed')], max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('images_url', models.JSONField(blank=True, default=list, help_text='List of image URLs')),
                ('monthly_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('hygiene_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('iot_enabled', models.BooleanField(default=False, help_text='USP #5')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=50)),
                ('floor', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(choices=[('SINGLE', 'Single'), ('DOUBLE', 'Double'), ('TRIPLE', 'Triple'), ('DORMITORY', 'Dormitory')], max_length=20)),
                ('base_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('electricity_reading', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('has_ac', models.BooleanField(default=False)),
                ('has_balcony', models.BooleanField(default=False)),
                ('has_wifi', models.BooleanField(default=True)),
                ('has_attached_bathroom', models.BooleanField(default=False)),
                ('window_count', models.IntegerField(default=1)),
                ('carpet_area_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('images_url', models.JSONField(blank=True, default=list)),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('MAINTENANCE', 'Maintenance')], default='AVAILABLE', max_length=20)),
            ],
        ),
    ]
