# Generated by Django 6.0 on 2026-01-03 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='current_tenant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_bed', to='users.tenantprofile'),
        ),
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='users.ownerprofile'),
        ),
        migrations.AddField(
            model_name='room',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='properties.property'),
        ),
        migrations.AddField(
            model_name='bed',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='properties.room'),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('property', 'room_number')},
        ),
        migrations.AlterUniqueTogether(
            name='bed',
            unique_together={('room', 'label')},
        ),
    ]
